server:
  port: 8081
spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/pnj
    username: root         # ✅ Thêm đúng username MySQL
    password:      # ✅ Thêm đúng password MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      schema-locations: classpath:schema.sql  # ✅ Đúng từ khóa classpath
# eureka:
#   client:
#     service-url:
#       defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
#       preferIpAddress: true
#     register-with-eureka: true
#     fetch-registry: true
eureka:
  client:
    enabled: false